version: "3.9"

services:
  nextapp:
    container_name: currency_converter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      OPEN_EXCHANGE_API_KEY: "${OPEN_EXCHANGE_API_KEY}"
      EXCHANGE_RATE_API_KEY: "${EXCHANGE_RATE_API_KEY}"
      EXCHANGE_API_PROVIDER: "${EXCHANGE_API_PROVIDER}"
    restart: unless-stopped
